### ISSUE TITLE
Running several audits in parallel results in FAILED audit

### ISSUE THREAD

**Issue by dutsik** [spotify/lighthouse-audit-service#55]
Hi there!

I am trying to setup lighthouse service for our internal project, we are planning to constantly run audit for diferent URLs. I am using oficial image: 

```
services:
  lh2:
    image: spotify/lighthouse-audit-service:latest
    environment:
      LAS_PORT: 1234
      PGUSER: user
      PGHOST: db
      PGPASSWORD: password
      PGDATABASE: dbname
    ports:
      - 1234:1234
```
When I do several POST requests with the following payload:
```
{
    "url": "https://www.google.com/",
    "options":
    {
        "awaitAuditCompleted": true,
                "chromePort": <randomPortNumber>
    }
}
```

I am always getting results only for the first successful response. the rest fails with the following error message in the logs:
` error: failed while running lighthouse audit.`

is it normal? or am I going smth wrong?

Thanks, Ivan
